### ISSUE TITLE
Adding support for format conversion and Media Library images

### ISSUE THREAD

**Issue by MilanLund** [liamgold/xperience-community-image-processing#2]
Hi @liamgold 

Thank you for this repository. It has helped me deliver a feature that a client requested but is not available in the core product and is not planned for future updates, as I confirmed with the Kentico team. The feature involves converting Media Library images to another format, specifically `webp`, to save data on page load.

I am considering creating a pull request to add support for this feature in Media Library images. Since you plan to deprecate this repository/nuget package when the _Media Assest Transformation_ feature arrives in the core product in October 2024, do you think it is worth creating such a pull request?

**Comment by liamgold** [comment]
Hi @MilanLund 

Glad you are finding the repository and package useful.

I've mainly added the warning about depreciation of the package to coincide with that feature release as I'd expect it to cover all of the features we'll need going forward. However, if the community still has a need for it after the feature is released I'm happy to support it ongoing in the future, and remove that warning message from the repository.

With this in mind, I am happy for you to provide feature enhancements, feel free to add support for file format conversions.

**Comment by MilanLund** [comment]
Okie dokie.
